ALTER PROCEDURE OrdComNac
--declare
@nIdOrdenCompra int,-- = 1479,
@cIdUsuario int --= 261218
AS
SELECT A.ID_ORDEN_COMPRA,
       A.FECHA,
	   C.NOMBRE,
	   C.DIRECCION,
	   C.CIUDAD,
	   C.CP,
	   C.TELEFONO1,
	   C.TELEFONO2,
	   C.TELEFONO3,
	   B.CANTIDAD,
	   B.ID_PRODUCTO,
	   B.DESCRIPCION,
	   B.PRECIO,
	   A.TOTAL,
	   A.DISCOUNT,
	   A.FREIGHT,
	   A.TAX,
	   A.OTROS_CARGOS,
	   D.NOMBRE as USUARIO,
	   A.MONEDA,
	   A.COMENTARIO,
	   *
FROM [dbo].[ORDEN_COMPRA] A, [dbo].[ORDEN_COMPRA_DETALLE] B, [dbo].[PROVEEDOR] C, [dbo].[USUARIOS] D
WHERE A.ID_ORDEN_COMPRA = B.ID_ORDEN_COMPRA
AND   A.ID_PROVEEDOR = C.ID_PROVEEDOR
AND   D.ID_USUARIO = A.ID_USUARIO
AND   A.ID_ORDEN_COMPRA = @nIdOrdenCompra
AND   A.ID_USUARIO = @cIdUsuario